---
# SOURCE: https://github.com/geerlingguy/mac-dev-playbook/blob/df25444b3f08e1c5a2c7b941d0a49850514f9d98/.travis.yml
os: osx
sudo: required
language: objective-c
# 10.13 (see https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version)
osx_image: xcode9.3
xcode_sdk: macosx10.13

before_install:
  - brew tap bossjones/scarlett-deps
  - echo "xcodebuild -showsdks"; xcodebuild -showsdks
  - echo "TRAVIS_XCODE_SDK"; env
  - xcodebuild -showsdks | awk '/^$/{p=0};p; /OS X SDKs:/{p=1}'
  - _SDKPARAM=`xcodebuild -showsdks | awk '/^$/{p=0};p; /OS X SDKs:/{p=1}' | tail -1 | cut -f3`; echo "_SDKPARAM - ${_SDKPARAM}"

script:
  - brew install --verbose --with-python --devel bossjones/scarlett-deps/cmu-sphinxbase
  # - brew install --HEAD bossjones/scarlett-deps/cmu-sphinxtrain
  - brew install --verbose --with-python bossjones/scarlett-deps/cmu-pocketsphinx


# script:
#   - brew install Formula/cmu-sphinxbase.rb
#   # - brew install --HEAD Formula/cmu-sphinxbase@5prealpha.rb
#   # - brew install --HEAD Formula/cmu-pocketsphinx@prealpha.rb
